import { AIProvider, ShiftSummaryContext } from '../types';

function formatShiftType(type: string): string {
  return type.charAt(0) + type.slice(1).toLowerCase();
}

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });
}

/**
 * Mock Llama provider — simulates an external LLM response.
 * Replace with a real Llama API client without changing aiSummaryService.
 */
export class MockLlamaProvider implements AIProvider {
  readonly name = 'mock-llama';

  async generateShiftSummary(context: ShiftSummaryContext): Promise<string> {
    // Simulate network latency of an external AI call
    await new Promise((resolve) => setTimeout(resolve, 400));

    const { shift, incidents, alerts, tasks } = context;
    const shiftLabel = formatShiftType(shift.shiftType);
    const timeRange = `${formatTime(shift.startTime)} – ${formatTime(shift.endTime)}`;

    const lines: string[] = [
      '## Shift Overview',
      `${shiftLabel} shift (${timeRange}) operated by **${shift.operatorName}**. Status: ${shift.status}.`,
    ];

    if (shift.handoverNotes) {
      lines.push('', `Handover context: ${shift.handoverNotes}`);
    }

    lines.push('', '## Critical Incidents');
    if (incidents.critical.length === 0) {
      lines.push('No critical incidents recorded during this shift.');
    } else {
      incidents.critical.forEach((inc) => {
        lines.push(
          `- **${inc.title}** (${inc.severity}, ${inc.status})${inc.service ? ` — ${inc.service}` : ''}`
        );
      });
    }

    lines.push('', '## Open Issues');
    if (incidents.open.length === 0) {
      lines.push('No open or investigating incidents at end of shift.');
    } else {
      incidents.open.forEach((inc) => {
        lines.push(
          `- ${inc.title} [${inc.severity}] — ${inc.status}${inc.service ? ` (${inc.service})` : ''}`
        );
      });
    }

    lines.push('', '## Resolved Issues');
    if (incidents.resolved.length === 0) {
      lines.push('No incidents were resolved during this shift.');
    } else {
      incidents.resolved.forEach((inc) => {
        lines.push(`- ${inc.title}${inc.service ? ` (${inc.service})` : ''}`);
      });
    }

    if (alerts.length > 0) {
      lines.push('', '## Monitoring Alerts');
      alerts.slice(0, 5).forEach((a) => {
        lines.push(`- ${a.title} [${a.severity}] — ${a.service} (${a.status})`);
      });
      if (alerts.length > 5) {
        lines.push(`- _...and ${alerts.length - 5} additional alerts_`);
      }
    }

    lines.push('', '## Tasks for Next Shift');
    if (tasks.pending.length === 0) {
      lines.push('No pending tasks requiring handover.');
    } else {
      tasks.pending.forEach((t) => {
        lines.push(
          `- [${t.priority}] ${t.title}${t.assignee ? ` (assigned: ${t.assignee})` : ''}`
        );
      });
    }

    if (tasks.completed.length > 0) {
      lines.push('', '### Completed This Shift');
      tasks.completed.slice(0, 3).forEach((t) => {
        lines.push(`- ${t.title}`);
      });
    }

    lines.push('', '## Recommended Follow-up Actions');
    const actions: string[] = [];

    if (incidents.critical.length > 0) {
      actions.push(
        `Escalate and monitor critical incident: ${incidents.critical[0].title}`
      );
    }
    if (incidents.open.length > 0) {
      actions.push('Review all open incidents at start of next shift');
    }
    if (tasks.pending.some((t) => t.priority === 'HIGH')) {
      actions.push('Prioritize high-priority pending tasks from handover list');
    }
    if (alerts.some((a) => a.status === 'NEW')) {
      actions.push('Triage unacknowledged monitoring alerts');
    }
    if (actions.length === 0) {
      actions.push('Continue standard monitoring procedures');
      actions.push('Confirm all systems green at shift start');
    }

    actions.forEach((action, i) => {
      lines.push(`${i + 1}. ${action}`);
    });

    lines.push('', '---', '_Generated by ShiftSync AI (Mock Llama Provider)_');

    return lines.join('\n');
  }
}

export const mockLlamaProvider = new MockLlamaProvider();
